### ISSUE TITLE
Extra AJAX requests

### ISSUE THREAD

**Issue by votintsev** [kartik-v/yii2-widget-depdrop#22]
Hi!

I have code:
```php
// First select
<?= $form->field($model, 'category')->dropDownList(
    ArrayHelper::map(\app\models\Category::find()->all(), 'id', 'name')
) ?>

<?= $form->field($model, 'vendor')->widget(DepDrop::classname(), [
    'pluginOptions'=>[
        'depends' => [Html::getInputId($model, 'category')],
        'placeholder' => 'Select...',
        'url' => Url::to(['site/vendor']),
        'loadingText' => 'Loading child level 3 ...'
    ]
])?>

<?= $form->field($model, 'model_id')->widget(DepDrop::classname(), [
    'pluginOptions'=>[
        'depends'=>[
            Html::getInputId($model, 'category'),
            Html::getInputId($model, 'vendor')],
        'placeholder' => 'Select...',
        'url' => Url::to(['site/model'])
    ]
]) ?>
```

When i create new form and change first select i see 3 AJAX request:
1. POST /index.php?r=site/vendor HTTP/1.1
```
depdrop_parents[0]:1
depdrop_all_params[mymodel-category]:1
```
Its OK!

2. POST /index.php?r=site/model HTTP/1.1
```
depdrop_parents[0]:1
depdrop_parents[1]:Loading child level 3 ...
depdrop_all_params[mymodel-category]:1
depdrop_all_params[mymodel-vendor]:Loading child level 3 ...
```
Why send this request?

3. POST /index.php?r=site/model HTTP/1.1
```
depdrop_parents[0]:1
depdrop_parents[1]:
depdrop_all_params[mymodel-category]:1
depdrop_all_params[mymodel-vendor]:
```
Also controversial request.

**Comment by kartik-v** [comment]
It entirely depends on how you are configuring the `depends` property of the plugin. Ajax request will be fired for every dependent object changed across. Check the examples and demos. 

In your last dropdown, instead of 

```php
'depends'=>[
    Html::getInputId($model, 'category'),
    Html::getInputId($model, 'vendor')],
]
```

just set this
```php
'depends'=>[
    Html::getInputId($model, 'vendor')],
]
```

**Comment by kartik-v** [comment]
It entirely depends on how you are configuring the `depends` property of the plugin. Ajax request will be fired for every dependent object changed across. Read docs in detail and check the examples and demos.

In your last dropdown, instead of 

```php
'depends'=>[
    Html::getInputId($model, 'category'),
    Html::getInputId($model, 'vendor')],
]
```

just set this
```php
'depends'=>[
    Html::getInputId($model, 'vendor')],
]
```

and you will automatically see lesser ajax requests which may work for your use case.

Use multiple depends only if you may have complex `depends` setting where one dropdown depends on multiple dropdowns.

**Comment by kartik-v** [comment]
It entirely depends on how you are configuring the `depends` property of the plugin. Ajax request will be fired for every dependent object changed across. Read docs in detail and check the examples and demos.

In your last dropdown, instead of 

```php
'depends'=>[
    Html::getInputId($model, 'category'),
    Html::getInputId($model, 'vendor')],
]
```

just set this
```php
'depends'=>[
    Html::getInputId($model, 'vendor')],
]
```

and you will automatically see lesser ajax requests which may work for your use case.

Use multiple depends only if you may have complex `depends` setting where one dropdown depends on multiple dropdowns.

**Comment by votintsev** [comment]
Thanks for the very quick answer!

But still confuses me perform two consecutive requests to the same address (requests 2 and 3). What passed as a parameter value option loadingText and immediately transmit the same query, but with the correct parameter values of the second field?
