### ISSUE TITLE
Exception Unknown Method – yii\base\UnknownMethodException Calling unknown method: kartik\tabs\TabsX::isBs4()

### ISSUE THREAD

**Issue by nonaee** [kartik-v/yii2-widget-depdrop#65]
![image](https://user-images.githubusercontent.com/25002672/45943115-40436080-c00f-11e8-9cb3-25dc4e320296.png)

I try to use the tabX and i found this. What should i do.

**Comment by kartik-v** [comment]
This happens if you have an outdated dependencies in your composer package install (OR if you are just manually updating/overwriting the extension files instead of using composer). 

Run composer update to get the latest version of extensions along with their dependencies (for example `yii2-tabs-x` depends on `yii2-krajee-base` and it must be also updated/installed).
